### ISSUE TITLE
comments incomplete

### ISSUE THREAD

**Issue by mosharafMS** [mosharafMS/GC-iaas-webapp#13]
many commented sections like this one below from PreparingSQLAO.json 
is incomplete because there's , left before the comment. 

 /*"MachineName": "[parameters('sql0VMName')]",
                        "ResourceGroupName": "[parameters('ResourceGroupName')]",
                        "AutomationAccountName": "[parameters('AutomationAccountName')]",
                        "AzureAuthCreds": {
                            "UserName": "[parameters('AzureUsername')]",
                            "Password": "PrivateSettingsRef:AzurePassword"
                        },
                        "SubscriptionId": "[parameters('SubscriptionId')]",
                        "EnvironmentName": "[parameters('EnvironmentName')]"*/

**Comment by mosharafMS** [comment]
ARM process these comments as the RFC for JSON. Had to delete them all.

**Comment by mosharafMS** [comment]
@jomolesk it seems this code didn't have a successful run since the comments were preventing the execution.

**Comment by jomolesk** [comment]
@davoodharun can you advise here?

**Comment by mosharafMS** [comment]
fixed
