### ISSUE TITLE
predeployment script doesn't read paramters from azuredeploy.parameters.json

### ISSUE THREAD

**Issue by aqasrawi** [mosharafMS/GC-iaas-webapp#15]
The Orchestration_InitialSetup.ps1 script prompts for various parameters, some of which are already specified in the parameters.json file. If a user enters different parameters from what's in the JSON file, various errors are produced.  We should have a single source for the parameters file.

**Comment by mosharafMS** [comment]
I can work on this issue.

**Comment by mosharafMS** [comment]
will be handled in issue #22
